language: node_js
node_js: node
jobs:
  include:
    - stage: test
      script: npm test
    - stage: release
      script: skip
      env:
        # GITHUB_TOKEN brightspace-ui-intl
        secure: IWxGb9VFjYPzO4YewM66+tEofRNfFY9BROZbYau9zeCDl22gXO+Exv3+mAXbjN0AplXT2cm4mdy0XEcri2zCBulXp8zUcp5ecvxp5em4HA1xfr+i8asmBHt5/N6bn7Bn/g5NjlOxZS5ZgSxDNokh6XftyjK62qVf0TZlyB2FL2wMjjIterWtwB+Cw+gI9zieENmRMMbpYHwsDXvkDrd9jbkuetZjjAqjnbBD7rlIzEa6g1J+VUT+rIBKDH21P6yQuipC4EXc1Q5fUDRbGF6wvIVanWLHVmsqNqPkxMUO6L7FlL0hF/SFBSpsAVE2rpSdWW2BDnfYhNJ15tMV1R9f6SXAdFdt0oo4/vz+CbRIW/y7bwx/HUUrLx2PVB7V82chL+DxSQ4yG2Myq1rM2+sYrqUpBc770th0bdXIwpft9IwdHNyGeAaEN+jkqPe2Zor928VJpeIzEpHADn8nue29VahiCezVCc7aIvd9w1TdwyoTYMyTt2tnKh3UDx+eW1G9SVYoKkHJuKyUfkuiGzks7yxc11GcVdHgE/D3OVC20rXVKwk+Q5GGKdk7QW4YgDPRQEsp+22ANTHLb6IW2IbIVjDeYF4PtlK6G3pPBUAorDlutEYl6gBDBsm0OLPZ/HwaDtZu8Hu+4jPN6AuccvT7IDz4rRj7J8hIJOKpbjdpxxI=
        # NPM_TOKEN 372f......9cf9
        secure: W1tlMt1xHJv+D/43lv58eUOV/uKPX4P5VdvZJbYwB5O4bQ5BO4QeySl4wVvJ+dvRIoUskr+X01+ZQHamCNt7jvPr8jn+xfH/q1RsiDxhUcqFievl6cUYzCawrjRgSqFf1kQ2k7tbn2LPKazAX+kok9sx0UWSCNte+8yDSOOmMmP6JAbYUPJ+gSTSkuGf2R7Rv/CucEwRS7xvcoSZGu8GABMDIgxM4Mtkw1Ww8q+fmH70wYGMGXjWvDb+FMpD/tiAqd3G9Pdt29AfIsiRDrtBrMnczBn59aIcDu/Z36EvP2ZQLR4NFx+Hmt+azRcIWzgAZh6Nz8kHGBiVyWCcLhpHayM4T4zyzpq/JF8lgI/UIL7irAEpdkxq9uq5biSpYQW7eDGEJgWWuTmfDdxnWpno5t0/IeWSYu1uMpPAlUfZXFLzw/xFMOLAc6OM+4lsyi6k3/5xfgJyax50XPLijZsNOIAoAaOkvDzmSCrOJuEb4xjCVsZmFwCr1s8VOCO3l+ihwe2TSqN218y+yNWyjKgA2TB1q5NrBJtCPAdv/ysdPUL+QTYBJqhpEccOD9l3HBfn5bErL5GYMEIoE00CF5dI7basrX21fOMruUrKQUW4JTMQeVa3XaPBwpoeBfcN4fMuymG23SnpLgSwCo5bYpzkruscgE7MWGI2gp0EzfAoCJ0=
      deploy:
        provider: script
        skip_cleanup: true
        script:
        - npx semantic-release
